### PR TITLE
Add method to see if user or organization has sponsoring enabled

### PR DESCRIPTION
**Pull request by quintenbuis**
This PR will add the requested feature in [https://github.com/Astrotomic/opendor.me/issues/143](https://github.com/Astrotomic/opendor.me/issues/143)

PS. Could the label: `hacktoberfest-accepted` be added to the PR? 😄 🚀

### CODE REVIEW

**Review by Gummibeer — CHANGES_REQUESTED** [review]
Hey, thanks for the PR! 🎉
I think that the `viewer` and `login` Queries are missing.
Everything else looks good! 👍

**Comment by quintenbuis** [comment]
> Hey, thanks for the PR! 🎉 I think that the `viewer` and `login` Queries are missing. Everything else looks good! 👍

I've added them! 🙂

**Review by Gummibeer — APPROVED** [review]
Thanks 🎉

**Comment by quintenbuis** [comment]
@Gummibeer When will this get merged and tagged? Would love to work on Astrotomic/opendor.me#143 🚀

**Pull request closed without merging**
